### ISSUE TITLE
ProgressBar

### ISSUE THREAD

**Issue by MadMikeyB** [Elhebert/vue-fineuploader#51]
Hiya,

How do I get the progressbar to show?

I've imported the component and have passed it an instance of the fineuploader wrapper but I don't see it on the screen.

I see it in vue-devtools though? And the progress seems to increment far faster than the file upload actual progress...

Thanks!

**Comment by Elhebert** [comment]
Without additional data I can't know what is happening.

Can you give me some context, screenshots and code to help me understand what is happening.
